require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TermsController, type: :controller do

  before(:all){			
    @admin = Administrator.create!(account_attributes: {first_name: "Admin", last_name: "istrator", email: "admin@example.com",
			password: "admin", password_confirmation: "admin"}) 			
  }	
  after(:all){
	@admin.destroy
  }

  # This should return the minimal set of attributes required to create a valid
  # Term. As you add validations to Term, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {:order => 1,
	:title => "this is a title",
	:body => "this is a long body"
	}
  }

  let(:invalid_attributes) {
    {:order => 1,
	:title => "",
	:body => ""
	}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TermsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all terms as @terms" do
	  log_in_as(@admin.account)
      term = Term.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:terms)).to eq([term])
    end
  end

  describe "GET #show" do
    it "assigns the requested term as @term" do
	  log_in_as(@admin.account)
      term = Term.create! valid_attributes
      get :show, {:id => term.to_param}, valid_session
      expect(assigns(:term)).to eq(term)
    end
  end

  describe "GET #new" do
    it "assigns a new term as @term" do
	  log_in_as(@admin.account)
      get :new, {}, valid_session
      expect(assigns(:term)).to be_a_new(Term)
    end
  end

  describe "GET #edit" do
    it "assigns the requested term as @term" do
	  log_in_as(@admin.account)
      term = Term.create! valid_attributes
      get :edit, {:id => term.to_param}, valid_session
      expect(assigns(:term)).to eq(term)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Term" do
	    log_in_as(@admin.account)
        expect {
          post :create, {:term => valid_attributes}, valid_session
        }.to change(Term, :count).by(1)
      end

      it "assigns a newly created term as @term" do
	    log_in_as(@admin.account)
        post :create, {:term => valid_attributes}, valid_session
        expect(assigns(:term)).to be_a(Term)
        expect(assigns(:term)).to be_persisted
      end

      it "redirects to the created term" do
	    log_in_as(@admin.account)
        post :create, {:term => valid_attributes}, valid_session
        expect(response).to redirect_to(Term.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved term as @term" do
	    log_in_as(@admin.account)
        post :create, {:term => invalid_attributes}, valid_session
        expect(assigns(:term)).to be_a_new(Term)
      end

      it "re-renders the 'new' template" do
	    log_in_as(@admin.account)
        post :create, {:term => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {:order => 1,
		:title => "newtitle",
		:body => "newbody"
		}
      }

      it "updates the requested term" do
	    log_in_as(@admin.account)
        term = Term.create! valid_attributes
        put :update, {:id => term.to_param, :term => new_attributes}, valid_session
        term.reload
        expect(assigns(:term)).to eq(term)
      end

      it "assigns the requested term as @term" do
	    log_in_as(@admin.account)
        term = Term.create! valid_attributes
        put :update, {:id => term.to_param, :term => valid_attributes}, valid_session
        expect(assigns(:term)).to eq(term)
      end

      it "redirects to the term" do
	    log_in_as(@admin.account)
        term = Term.create! valid_attributes
        put :update, {:id => term.to_param, :term => valid_attributes}, valid_session
        expect(response).to redirect_to(term)
      end
    end

    context "with invalid params" do
      it "assigns the term as @term" do
	    log_in_as(@admin.account)
        term = Term.create! valid_attributes
        put :update, {:id => term.to_param, :term => invalid_attributes}, valid_session
        expect(assigns(:term)).to eq(term)
      end

      it "re-renders the 'edit' template" do
	    log_in_as(@admin.account)
        term = Term.create! valid_attributes
        put :update, {:id => term.to_param, :term => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested term" do
	  log_in_as(@admin.account)
      term = Term.create! valid_attributes
      expect {
        delete :destroy, {:id => term.to_param}, valid_session
      }.to change(Term, :count).by(-1)
    end

    it "redirects to the terms list" do
	  log_in_as(@admin.account)
      term = Term.create! valid_attributes
      delete :destroy, {:id => term.to_param}, valid_session
      expect(response).to redirect_to(terms_url)
    end
  end

end
